# Default initial positions for name's ros2_control fake system

initial_positions:
  elbow_joint: 0.00
  robotiq_85_left_knuckle_joint: 0.00
  shoulder_lift_joint: 0.00
  shoulder_pan_joint: 0.00
  wrist_1_joint: 0.00
  wrist_2_joint: 0.00
  wrist_3_joint: 0.00